# https://docs.travis-ci.com/user/languages/cpp/
# https://launchpad.net/~beineri/+archive/ubuntu/opt-qt59-trusty
language: cpp
dist: trusty
sudo: required
compiler: gcc
addons:
  apt:
    sources:
      - sourceline: ppa:beineri/opt-qt59-trusty
    packages:
      - qt59base
      - qt593d
      - qt59declarative
      - qt59location
      - qt59quickcontrols2
install:
  - source /opt/qt59/bin/qt59-env.sh
  - qmake -v
before_script:
  - mkdir -p build && cd build
  - qmake PREFIX=/usr ../src
script:
  - make
